apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  creationTimestamp: null
  name: "2959103525227171661"
  namespace: default
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/airren/flux
status: {}
