apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust3098243976072588083
  namespace: default
spec:
  interval: 5m0s
  path: clusters/akraino_scc_overlay1+edge-1/context/3098243976072588083
  prune: true
  sourceRef:
    kind: GitRepository
    name: "3098243976072588083"
  targetNamespace: default
status: {}
