apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust4380216551849609863
  namespace: default
spec:
  interval: 5m0s
  path: clusters/akraino_scc_overlay1+edge-1/context/4380216551849609863
  prune: true
  sourceRef:
    kind: GitRepository
    name: "4380216551849609863"
  targetNamespace: default
status: {}
