apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust4546005521101871639
  namespace: default
spec:
  interval: 5m0s
  path: clusters/akraino_scc_overlay1+edge-1/context/4546005521101871639
  prune: true
  sourceRef:
    kind: GitRepository
    name: "4546005521101871639"
  targetNamespace: default
status: {}
